name: PlantUML End-to-End Action
description: A GitHub Action for creating a PlantUML file from a Python module and exporting it as an image.
inputs:
  puml_version:
    description: PlantUML software version
    default: "latest"
    required: true
  pip_install_deps_cmd:
    description: |
      The command that installs your project's dependencies require to have py2puml import your project. Typically, that'd be e.g.
      `pip install .` or `pip install .[docs]`. If the command doesn't install a version of `py2puml`, the latest version
      will be auto-installed.
    required: true
  path:
    description: the filepath to the domain following the py2puml definition
    required: true
  module:
    description: the module name of the domain following the py2puml definition
    required: true
  output_dir:
    description: the directory where the PNG should be saved to. File names default to the module name, but differ by file extension (.puml/.png).
    default: diagrams
    required: true
runs:
  using: docker
  image: Dockerfile
branding:
  color: green
  icon: code
